from enum import Enum

class ProjectClassification(str, Enum):
    ELEGIVEL = "Elegível"
    COM_RESSALVAS = "Com ressalvas"
    NAO_ELEGIVEL = "Não elegível"
    EVIDENCIA_INSUFICIENTE = "Evidência insuficiente"

class CriteriaState(str, Enum):
    DEMONSTRADA_NO_RECORTE = "DEMONSTRADA NO RECORTE"
    NAO_DEMONSTRADA = "NÃO DEMONSTRADA"
    INVESTIGADA = "INVESTIGADA"
    NAO_CARACTERIZADA = "NÃO CARACTERIZADA"
    DOCUMENTADA = "DOCUMENTADA"
    DOCUMENTADA_COMO_ACEITE = "DOCUMENTADA COMO ACEITE"
    DOCUMENTADA_PARA_CONFIGURACAO = "DOCUMENTADA PARA A CONFIGURAÇÃO"
    DOCUMENTADA_NO_ESCOPO = "DOCUMENTADA NO ESCOPO"
    DOCUMENTADA_COM_LIMITE = "DOCUMENTADA COM LIMITE"
    INDETERMINADA = "INDETERMINADA"
    ALEGADA_NAO_VERIFICAVEL = "ALEGADA, NÃO VERIFICÁVEL"
    PARCIAL = "PARCIAL"
    INSUFICIENTE_PARA_NUCLEO = "INSUFICIENTE PARA O NÚCLEO ALEGADO"